project:
  type: website

website:
  title: "Tamisha D. Segbefia"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: example_analysis.qmd
        text: Example Analysis

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

